load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "console",
    srcs = [
        "failure.go",
        "output.go",
    ],
    importpath = "cli/pkg/console",
    visibility = ["//visibility:public"],
)
