module github.com/airyhq/airy

go 1.15

// Used to update go_repositories.bzl with Gazelle
// Automatically generated by running //tools/update-deps

require (
	github.com/alicebob/miniredis/v2 v2.13.3
	github.com/go-redis/redis/v8 v8.2.2
	github.com/spf13/cobra v1.1.1
	github.com/aws/aws-sdk-go-v2/config v1.1.1
	github.com/aws/aws-sdk-go-v2/service/ec2 v1.1.1
	github.com/aws/aws-sdk-go-v2/service/eks v1.1.1
	github.com/imdario/mergo v0.3.11 // indirect
	github.com/kr/pretty v0.2.1
	github.com/mitchellh/go-homedir v1.1.0
	github.com/spf13/cast v1.3.1 // indirect
	github.com/spf13/viper v1.7.1
	goji.io v2.0.2+incompatible
	gopkg.in/yaml.v2 v2.4.0
	k8s.io/api v0.20.1
	k8s.io/apimachinery v0.20.1
	k8s.io/client-go v0.20.1
	k8s.io/klog v1.0.0
	golang.org/x/time v0.0.0-20201208040808-7e3f01d25324 // indirect
	k8s.io/utils v0.0.0-20201110183641-67b214c5f920 // indirect
	github.com/stretchr/testify v1.6.1
	golang.org/x/mod v0.4.1
)
