module github.com/airyhq/airy

go 1.16

// Used to update go_repositories.bzl with Gazelle
// Automatically generated by running //tools/update-deps

require (
	github.com/Shopify/sarama v1.28.0
	github.com/TwinProduction/go-color v1.0.0
	github.com/aws/aws-sdk-go v1.37.29
	github.com/aws/aws-sdk-go-v2/config v1.1.1
	github.com/aws/aws-sdk-go-v2/service/ec2 v1.1.1
	github.com/aws/aws-sdk-go-v2/service/eks v1.1.1
	github.com/aws/aws-sdk-go-v2/service/iam v1.1.1
	github.com/beanstalkd/go-beanstalk v0.1.0
	github.com/imdario/mergo v0.3.11 // indirect
	github.com/jpillora/backoff v1.0.0
	github.com/kr/pretty v0.2.1
	github.com/mitchellh/go-homedir v1.1.0
	github.com/riferrei/srclient v0.2.1
	github.com/spf13/cast v1.3.1 // indirect
	github.com/spf13/cobra v1.1.1
	github.com/spf13/viper v1.7.1
	github.com/stretchr/testify v1.7.0
	github.com/thanhpk/randstr v1.0.4
	github.com/txn2/txeh v1.3.0
	goji.io v2.0.2+incompatible
	golang.org/x/mod v0.4.1
	golang.org/x/time v0.0.0-20201208040808-7e3f01d25324 // indirect
	gopkg.in/yaml.v2 v2.4.0
	k8s.io/api v0.19.0
	k8s.io/apimachinery v0.19.0
	k8s.io/client-go v0.19.0
	k8s.io/klog v1.0.0
	k8s.io/utils v0.0.0-20201110183641-67b214c5f920 // indirect
)
