load("@com_github_airyhq_bazel_tools//web:typescript.bzl", "ts_library")

package(default_visibility = ["//visibility:public"])

ts_library(
    name = "types",
    srcs = glob([
        "**/*.d.ts",
    ]),
)
