# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "mrvantage/centos7-minikube"
  config.vm.box_version = "1.1.1-20200929"


    vb.customize ["modifyvm", :id, "--memory", "4096", "--cpus", "2"]
  end


  config.vm.provision "file", source: "topics.sh", destination: "/home/vagrant/topics.sh"
  config.vm.provision "file", source: "create-topics.sh", destination: "/home/vagrant/create-topics.sh"
  config.vm.provision "file", source: "kafka-client.yaml", destination: "/home/vagrant/kafka-client.yaml"
  config.vm.synced_folder "deployments/", "/home/vagrant/"

  config.vm.provision :shell, path: "bootstrap.sh"

end
