# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "mrvantage/centos7-minikube"
  config.vm.box_version = "1.1.1-20200929"


  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4096", "--cpus", "2"]
  end
  
  config.vm.provision :shell, path: "provision.sh"

end
