# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "mrvantage/centos7-minikube"
  config.vm.box_version = "1.1.1-20200929"


  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "6054", "--cpus", "3"]
  end


  config.vm.provision "file", source: "topics.sh", destination: "/home/vagrant/topics.sh"
  config.vm.provision "file", source: "create-topics.sh", destination: "/home/vagrant/create-topics.sh"
  config.vm.provision "file", source: "kafka-client.yaml", destination: "/home/vagrant/kafka-client.yaml"
  config.vm.provision "file", source: "deployments/api-admin.yaml", destination: "/home/vagrant/api-admin.yaml"
  config.vm.provision "file", source: "deployments/api-auth.yaml", destination: "/home/vagrant/api-auth.yaml"
  config.vm.provision "file", source: "deployments/api-communication.yaml", destination: "/home/vagrant/api-communication.yaml"
  config.vm.provision "file", source: "deployments/events-router.yaml", destination: "/home/vagrant/events-router.yaml"
  
  config.vm.provision :shell, path: "provision.sh"

end
