package(default_visibility = ["//visibility:public"])

filegroup(
    name = "golden_files",
    srcs = [
        "cli.app.reset.no-args.golden",
        "cli.kafka.consumergroup.golden",
        "cli.kafka.status.golden",
        "cli.no-args.golden",
    ],
)
