load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "cache",
    srcs = ["deployed_charts.go"],
    importpath = "github.com/airyhq/airy/infrastructure/controller/pkg/cache",
    visibility = ["//visibility:public"],
)
