export enum ConnectorName {
  apiAdmin = 'api-admin',
  apiCommunication = 'api-communication',
  apiContacts = 'api-contacts',
  apiWebsocket = 'api-websocket',
  cloudConnector = 'cloud-connector',
  dialogflowConnector = 'dialog-connector',
  enterpriseMobileAuth = 'enterprise-mobile-auth',
  salesforceContactsIngestion = 'salesforce-contacts-ingestion',
  enterprisePushNotification = 'enterprise-push-notifiction',
  frontendControlCenter = 'frontend-control-center',
  frontendInbox = 'frontend-inbox',
  integrationSourceApi = 'integration-source-api',
  integrationWebhook = 'integration-webhook',
  mediaResolver = 'media-resolver',
  sourcesChatPlugin = 'sources-chatplugin',
  sourcesFacebook = 'sources-facebook',
  sourcesGoogle = 'sources-google',
  sourcesTwilio = 'sources-twilio',
  sourcesWhatsappBusinessCloud = 'sources-whatsapp-business-cloud',
  sourcesViber = 'sources-viber',
  rasaConnector = 'rasa-connector',
  zendenkConnector = 'zendesk-connector',
}
