load("@com_github_airyhq_bazel_tools//web:typescript.bzl", "ts_library")

package(default_visibility = ["//visibility:public"])

ts_library(
    name = "services",
    deps = [
        "//lib/typescript/httpclient",
        "//lib/typescript/types",
    ],
)
