# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "airy-core", autostart: true do |airy_core|
    airy_core.vm.box = "mrvantage/centos7-minikube"
    airy_core.vm.box_version = "1.1.1-20200929"
    airy_core.vm.network "private_network", ip: "192.168.50.5"
    airy_core.vm.provision "core", type: "shell" do |c|
      c.inline = "/vagrant/scripts/provision.sh"
    end
    airy_core.vm.provision "user-data", type: "shell" do |u|
      u.inline = "/vagrant/scripts/user-input.sh"
    end
    airy_core.vm.provider "virtualbox" do |vbox|
      vbox.cpus = 3
      vbox.memory = 6144
      vbox.customize [
        "modifyvm", :id, "--audio", "none"
      ]
    end
    airy_core.trigger.after [:up, :reload] do |status|
      status.name = "status"
      status.run_remote = {inline: "/vagrant/scripts/status.sh"}
    end
  end
end
