load("//tools/build:java_library.bzl", "custom_java_library")

custom_java_library(
    name = "url",
    srcs = glob(["src/main/java/co/airy/url/**/*.java"]),
    visibility = ["//visibility:public"],
)
